name: "Bug report"
description: "Report a reproducible issue"
title: "[Bug]: "
labels: [ "bug" ]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "What happened?"
      placeholder: "Describe the issue clearly."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "Provide a minimal reproduction."
      placeholder: "1. Run ...\n2. ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      placeholder: "What did you expect to happen?"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior"
      placeholder: "What actually happened?"
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Include OS, runtime version, and project version."
      placeholder: "macOS 14, Node 20.10.0, tmln 1.1.0"
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist"
      options:
        - label: "I'm using the latest version"
          required: true
        - label: "I've searched existing issues"
          required: true
