name: "Feature request"
description: "Suggest an improvement or new feature"
title: "[Feature]: "
labels: [ "enhancement" ]
body:
  - type: textarea
    id: problem
    attributes:
      label: "What problem does this solve?"
      description: "Describe the pain point or use case."
      placeholder: "I often need to... but the project currently..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Proposed solution"
      description: "How would you like this to work?"
      placeholder: "It would be great if..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives considered"
      description: "Any workarounds or alternative approaches?"
      placeholder: "I've tried... but..."
    validations:
      required: false
